-- 코드를 작성해주세요
SELECT 
    SUM(g.SCORE) AS SCORE,
    g.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM HR_EMPLOYEES e
INNER JOIN HR_GRADE g ON g.EMP_NO = e.EMP_NO
WHERE g.YEAR = 2022
GROUP BY g.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
ORDER BY SCORE DESC
limit 0,1;